/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GraduatesRouteImport } from './routes/graduates'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'
import { Route as ApiUsersIndexRouteImport } from './routes/api/users/index'
import { Route as ApiSchedulesIndexRouteImport } from './routes/api/schedules/index'
import { Route as ApiRoundsIndexRouteImport } from './routes/api/rounds/index'
import { Route as ApiGroupsIndexRouteImport } from './routes/api/groups/index'
import { Route as ApiGraduatesIndexRouteImport } from './routes/api/graduates/index'
import { Route as ApiDiplomasIndexRouteImport } from './routes/api/diplomas/index'
import { Route as ApiAttendsIndexRouteImport } from './routes/api/attends/index'
import { Route as ApiUsersIdRouteImport } from './routes/api/users/$id'
import { Route as ApiSchedulesIdRouteImport } from './routes/api/schedules/$id'
import { Route as ApiRoundsIdRouteImport } from './routes/api/rounds/$id'
import { Route as ApiLoginStaffRouteImport } from './routes/api/login/staff'
import { Route as ApiLoginGraduateRouteImport } from './routes/api/login/graduate'
import { Route as ApiDiplomasIdRouteImport } from './routes/api/diplomas/$id'
import { Route as ApiAttendsIdRouteImport } from './routes/api/attends/$id'
import { Route as ApiGraduatesStudentStudent_idRouteImport } from './routes/api/graduates/student/$student_id'
import { Route as ApiDiplomasStudentStudent_idRouteImport } from './routes/api/diplomas/student/$student_id'
import { Route as ApiDiplomasGraduatesGraduate_idRouteImport } from './routes/api/diplomas/graduates/$graduate_id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GraduatesRoute = GraduatesRouteImport.update({
  id: '/graduates',
  path: '/graduates',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SettingsRoute,
} as any)
const ApiUsersIndexRoute = ApiUsersIndexRouteImport.update({
  id: '/api/users/',
  path: '/api/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSchedulesIndexRoute = ApiSchedulesIndexRouteImport.update({
  id: '/api/schedules/',
  path: '/api/schedules/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoundsIndexRoute = ApiRoundsIndexRouteImport.update({
  id: '/api/rounds/',
  path: '/api/rounds/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGroupsIndexRoute = ApiGroupsIndexRouteImport.update({
  id: '/api/groups/',
  path: '/api/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGraduatesIndexRoute = ApiGraduatesIndexRouteImport.update({
  id: '/api/graduates/',
  path: '/api/graduates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiplomasIndexRoute = ApiDiplomasIndexRouteImport.update({
  id: '/api/diplomas/',
  path: '/api/diplomas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttendsIndexRoute = ApiAttendsIndexRouteImport.update({
  id: '/api/attends/',
  path: '/api/attends/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersIdRoute = ApiUsersIdRouteImport.update({
  id: '/api/users/$id',
  path: '/api/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSchedulesIdRoute = ApiSchedulesIdRouteImport.update({
  id: '/api/schedules/$id',
  path: '/api/schedules/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoundsIdRoute = ApiRoundsIdRouteImport.update({
  id: '/api/rounds/$id',
  path: '/api/rounds/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoginStaffRoute = ApiLoginStaffRouteImport.update({
  id: '/api/login/staff',
  path: '/api/login/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoginGraduateRoute = ApiLoginGraduateRouteImport.update({
  id: '/api/login/graduate',
  path: '/api/login/graduate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiplomasIdRoute = ApiDiplomasIdRouteImport.update({
  id: '/api/diplomas/$id',
  path: '/api/diplomas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttendsIdRoute = ApiAttendsIdRouteImport.update({
  id: '/api/attends/$id',
  path: '/api/attends/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGraduatesStudentStudent_idRoute =
  ApiGraduatesStudentStudent_idRouteImport.update({
    id: '/api/graduates/student/$student_id',
    path: '/api/graduates/student/$student_id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDiplomasStudentStudent_idRoute =
  ApiDiplomasStudentStudent_idRouteImport.update({
    id: '/api/diplomas/student/$student_id',
    path: '/api/diplomas/student/$student_id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDiplomasGraduatesGraduate_idRoute =
  ApiDiplomasGraduatesGraduate_idRouteImport.update({
    id: '/api/diplomas/graduates/$graduate_id',
    path: '/api/diplomas/graduates/$graduate_id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/graduates': typeof GraduatesRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/users': typeof SettingsUsersRoute
  '/api/attends/$id': typeof ApiAttendsIdRoute
  '/api/diplomas/$id': typeof ApiDiplomasIdRoute
  '/api/login/graduate': typeof ApiLoginGraduateRoute
  '/api/login/staff': typeof ApiLoginStaffRoute
  '/api/rounds/$id': typeof ApiRoundsIdRoute
  '/api/schedules/$id': typeof ApiSchedulesIdRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/attends': typeof ApiAttendsIndexRoute
  '/api/diplomas': typeof ApiDiplomasIndexRoute
  '/api/graduates': typeof ApiGraduatesIndexRoute
  '/api/groups': typeof ApiGroupsIndexRoute
  '/api/rounds': typeof ApiRoundsIndexRoute
  '/api/schedules': typeof ApiSchedulesIndexRoute
  '/api/users': typeof ApiUsersIndexRoute
  '/api/diplomas/graduates/$graduate_id': typeof ApiDiplomasGraduatesGraduate_idRoute
  '/api/diplomas/student/$student_id': typeof ApiDiplomasStudentStudent_idRoute
  '/api/graduates/student/$student_id': typeof ApiGraduatesStudentStudent_idRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/graduates': typeof GraduatesRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/users': typeof SettingsUsersRoute
  '/api/attends/$id': typeof ApiAttendsIdRoute
  '/api/diplomas/$id': typeof ApiDiplomasIdRoute
  '/api/login/graduate': typeof ApiLoginGraduateRoute
  '/api/login/staff': typeof ApiLoginStaffRoute
  '/api/rounds/$id': typeof ApiRoundsIdRoute
  '/api/schedules/$id': typeof ApiSchedulesIdRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/attends': typeof ApiAttendsIndexRoute
  '/api/diplomas': typeof ApiDiplomasIndexRoute
  '/api/graduates': typeof ApiGraduatesIndexRoute
  '/api/groups': typeof ApiGroupsIndexRoute
  '/api/rounds': typeof ApiRoundsIndexRoute
  '/api/schedules': typeof ApiSchedulesIndexRoute
  '/api/users': typeof ApiUsersIndexRoute
  '/api/diplomas/graduates/$graduate_id': typeof ApiDiplomasGraduatesGraduate_idRoute
  '/api/diplomas/student/$student_id': typeof ApiDiplomasStudentStudent_idRoute
  '/api/graduates/student/$student_id': typeof ApiGraduatesStudentStudent_idRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/graduates': typeof GraduatesRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/users': typeof SettingsUsersRoute
  '/api/attends/$id': typeof ApiAttendsIdRoute
  '/api/diplomas/$id': typeof ApiDiplomasIdRoute
  '/api/login/graduate': typeof ApiLoginGraduateRoute
  '/api/login/staff': typeof ApiLoginStaffRoute
  '/api/rounds/$id': typeof ApiRoundsIdRoute
  '/api/schedules/$id': typeof ApiSchedulesIdRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/attends/': typeof ApiAttendsIndexRoute
  '/api/diplomas/': typeof ApiDiplomasIndexRoute
  '/api/graduates/': typeof ApiGraduatesIndexRoute
  '/api/groups/': typeof ApiGroupsIndexRoute
  '/api/rounds/': typeof ApiRoundsIndexRoute
  '/api/schedules/': typeof ApiSchedulesIndexRoute
  '/api/users/': typeof ApiUsersIndexRoute
  '/api/diplomas/graduates/$graduate_id': typeof ApiDiplomasGraduatesGraduate_idRoute
  '/api/diplomas/student/$student_id': typeof ApiDiplomasStudentStudent_idRoute
  '/api/graduates/student/$student_id': typeof ApiGraduatesStudentStudent_idRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/graduates'
    | '/login'
    | '/settings'
    | '/settings/users'
    | '/api/attends/$id'
    | '/api/diplomas/$id'
    | '/api/login/graduate'
    | '/api/login/staff'
    | '/api/rounds/$id'
    | '/api/schedules/$id'
    | '/api/users/$id'
    | '/api/attends'
    | '/api/diplomas'
    | '/api/graduates'
    | '/api/groups'
    | '/api/rounds'
    | '/api/schedules'
    | '/api/users'
    | '/api/diplomas/graduates/$graduate_id'
    | '/api/diplomas/student/$student_id'
    | '/api/graduates/student/$student_id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/graduates'
    | '/login'
    | '/settings'
    | '/settings/users'
    | '/api/attends/$id'
    | '/api/diplomas/$id'
    | '/api/login/graduate'
    | '/api/login/staff'
    | '/api/rounds/$id'
    | '/api/schedules/$id'
    | '/api/users/$id'
    | '/api/attends'
    | '/api/diplomas'
    | '/api/graduates'
    | '/api/groups'
    | '/api/rounds'
    | '/api/schedules'
    | '/api/users'
    | '/api/diplomas/graduates/$graduate_id'
    | '/api/diplomas/student/$student_id'
    | '/api/graduates/student/$student_id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/graduates'
    | '/login'
    | '/settings'
    | '/settings/users'
    | '/api/attends/$id'
    | '/api/diplomas/$id'
    | '/api/login/graduate'
    | '/api/login/staff'
    | '/api/rounds/$id'
    | '/api/schedules/$id'
    | '/api/users/$id'
    | '/api/attends/'
    | '/api/diplomas/'
    | '/api/graduates/'
    | '/api/groups/'
    | '/api/rounds/'
    | '/api/schedules/'
    | '/api/users/'
    | '/api/diplomas/graduates/$graduate_id'
    | '/api/diplomas/student/$student_id'
    | '/api/graduates/student/$student_id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  GraduatesRoute: typeof GraduatesRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  ApiAttendsIdRoute: typeof ApiAttendsIdRoute
  ApiDiplomasIdRoute: typeof ApiDiplomasIdRoute
  ApiLoginGraduateRoute: typeof ApiLoginGraduateRoute
  ApiLoginStaffRoute: typeof ApiLoginStaffRoute
  ApiRoundsIdRoute: typeof ApiRoundsIdRoute
  ApiSchedulesIdRoute: typeof ApiSchedulesIdRoute
  ApiUsersIdRoute: typeof ApiUsersIdRoute
  ApiAttendsIndexRoute: typeof ApiAttendsIndexRoute
  ApiDiplomasIndexRoute: typeof ApiDiplomasIndexRoute
  ApiGraduatesIndexRoute: typeof ApiGraduatesIndexRoute
  ApiGroupsIndexRoute: typeof ApiGroupsIndexRoute
  ApiRoundsIndexRoute: typeof ApiRoundsIndexRoute
  ApiSchedulesIndexRoute: typeof ApiSchedulesIndexRoute
  ApiUsersIndexRoute: typeof ApiUsersIndexRoute
  ApiDiplomasGraduatesGraduate_idRoute: typeof ApiDiplomasGraduatesGraduate_idRoute
  ApiDiplomasStudentStudent_idRoute: typeof ApiDiplomasStudentStudent_idRoute
  ApiGraduatesStudentStudent_idRoute: typeof ApiGraduatesStudentStudent_idRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graduates': {
      id: '/graduates'
      path: '/graduates'
      fullPath: '/graduates'
      preLoaderRoute: typeof GraduatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/api/users/': {
      id: '/api/users/'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/schedules/': {
      id: '/api/schedules/'
      path: '/api/schedules'
      fullPath: '/api/schedules'
      preLoaderRoute: typeof ApiSchedulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rounds/': {
      id: '/api/rounds/'
      path: '/api/rounds'
      fullPath: '/api/rounds'
      preLoaderRoute: typeof ApiRoundsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/groups/': {
      id: '/api/groups/'
      path: '/api/groups'
      fullPath: '/api/groups'
      preLoaderRoute: typeof ApiGroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graduates/': {
      id: '/api/graduates/'
      path: '/api/graduates'
      fullPath: '/api/graduates'
      preLoaderRoute: typeof ApiGraduatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diplomas/': {
      id: '/api/diplomas/'
      path: '/api/diplomas'
      fullPath: '/api/diplomas'
      preLoaderRoute: typeof ApiDiplomasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attends/': {
      id: '/api/attends/'
      path: '/api/attends'
      fullPath: '/api/attends'
      preLoaderRoute: typeof ApiAttendsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/$id': {
      id: '/api/users/$id'
      path: '/api/users/$id'
      fullPath: '/api/users/$id'
      preLoaderRoute: typeof ApiUsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/schedules/$id': {
      id: '/api/schedules/$id'
      path: '/api/schedules/$id'
      fullPath: '/api/schedules/$id'
      preLoaderRoute: typeof ApiSchedulesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rounds/$id': {
      id: '/api/rounds/$id'
      path: '/api/rounds/$id'
      fullPath: '/api/rounds/$id'
      preLoaderRoute: typeof ApiRoundsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/login/staff': {
      id: '/api/login/staff'
      path: '/api/login/staff'
      fullPath: '/api/login/staff'
      preLoaderRoute: typeof ApiLoginStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/login/graduate': {
      id: '/api/login/graduate'
      path: '/api/login/graduate'
      fullPath: '/api/login/graduate'
      preLoaderRoute: typeof ApiLoginGraduateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diplomas/$id': {
      id: '/api/diplomas/$id'
      path: '/api/diplomas/$id'
      fullPath: '/api/diplomas/$id'
      preLoaderRoute: typeof ApiDiplomasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attends/$id': {
      id: '/api/attends/$id'
      path: '/api/attends/$id'
      fullPath: '/api/attends/$id'
      preLoaderRoute: typeof ApiAttendsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graduates/student/$student_id': {
      id: '/api/graduates/student/$student_id'
      path: '/api/graduates/student/$student_id'
      fullPath: '/api/graduates/student/$student_id'
      preLoaderRoute: typeof ApiGraduatesStudentStudent_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diplomas/student/$student_id': {
      id: '/api/diplomas/student/$student_id'
      path: '/api/diplomas/student/$student_id'
      fullPath: '/api/diplomas/student/$student_id'
      preLoaderRoute: typeof ApiDiplomasStudentStudent_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diplomas/graduates/$graduate_id': {
      id: '/api/diplomas/graduates/$graduate_id'
      path: '/api/diplomas/graduates/$graduate_id'
      fullPath: '/api/diplomas/graduates/$graduate_id'
      preLoaderRoute: typeof ApiDiplomasGraduatesGraduate_idRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsUsersRoute: typeof SettingsUsersRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsUsersRoute: SettingsUsersRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  GraduatesRoute: GraduatesRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ApiAttendsIdRoute: ApiAttendsIdRoute,
  ApiDiplomasIdRoute: ApiDiplomasIdRoute,
  ApiLoginGraduateRoute: ApiLoginGraduateRoute,
  ApiLoginStaffRoute: ApiLoginStaffRoute,
  ApiRoundsIdRoute: ApiRoundsIdRoute,
  ApiSchedulesIdRoute: ApiSchedulesIdRoute,
  ApiUsersIdRoute: ApiUsersIdRoute,
  ApiAttendsIndexRoute: ApiAttendsIndexRoute,
  ApiDiplomasIndexRoute: ApiDiplomasIndexRoute,
  ApiGraduatesIndexRoute: ApiGraduatesIndexRoute,
  ApiGroupsIndexRoute: ApiGroupsIndexRoute,
  ApiRoundsIndexRoute: ApiRoundsIndexRoute,
  ApiSchedulesIndexRoute: ApiSchedulesIndexRoute,
  ApiUsersIndexRoute: ApiUsersIndexRoute,
  ApiDiplomasGraduatesGraduate_idRoute: ApiDiplomasGraduatesGraduate_idRoute,
  ApiDiplomasStudentStudent_idRoute: ApiDiplomasStudentStudent_idRoute,
  ApiGraduatesStudentStudent_idRoute: ApiGraduatesStudentStudent_idRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
